      - name: Compile Release Kext
        run: |
          xcodebuild \
            -project "Lilu.xcodeproj" \
            -scheme "Lilu" \
            -configuration Release \
            -arch x86_64 \
            -allowProvisioningUpdates \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
