name: CI

on:
  push:
    branches: [ master, main, origin ]
  pull_request:
    branches: [ master, main, origin ]
  workflow_dispatch:

jobs:
  build:
    name: Build Patched Lilu
    runs-on: macos-latest
    steps:
      - name: Checkout Lilu Code
        uses: actions/checkout@v4

      - name: Fetch MacKernelSDK Headers
        uses: actions/checkout@v4
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK

      - name: Compile Release Kext
        run: |
          xcodebuild \
            -project "Lilu.xcodeproj" \
            -scheme "Lilu" \
            -configuration Release \
            -arch x86_64 \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Zip and Upload Finished Kext
        uses: actions/upload-artifact@v4
        with:
          name: Patched-Lilu-Kext
          path: build/Release/*.kext
